### PR TITLE
Add DICOM testcases for issue #1067

### PR DESCRIPTION
**Pull request by Pandede**
Related to PR https://github.com/imageio/imageio/pull/1069.

### CODE REVIEW

**Comment by FirefoxMetzger** [comment]
Reposting @Pandede 's comment about the image here for future reference:

---

I just generate the fake data to reproduce the issue #1067 via `pydicom`:
```python
import random
from pathlib import Path
from uuid import uuid4

import pydicom


def remake_test_data(file: Path, x: float, y: float, z: float) -> pydicom.Dataset:
    # Related to the scenario in issue #1067,
    # All the DICOM files have the identical `InstanceNumber` but shuffled `ImagePositionPatient`
    ds = pydicom.dcmread(file)
    ds.InstanceNumber = str(1)
    ds.ImagePositionPatient = [str(x), str(y), str(z)]
    return ds


def generate_fake_dicom(src: Path, dst: Path):
    # Remake the data with UUID prefix to avoid the OS list the filenames in ascending order
    shuffled_src = list(src.glob('*'))
    random.shuffle(shuffled_src)
    for i, file in enumerate(shuffled_src):
        dataset = remake_test_data(file, x=10, x=10, z=i)
        # The pattern of `random_filename`: <uuid>_z01, <uuid>_z02...
        random_filename = dst / f'{uuid4().hex}_z{i:02}'
        dataset.save_as(random_filename)

if __name__ == '__main__':
    # The source files are unzipped from `dicom_sample1.zip` in the repository `imageio/test_images`
    source = Path('dicom_sample1')
    # The directory to store the modified testdata
    modified = Path('modified_dicom_sample1')

    generate_fake_dicom(source, modified)
```
These testcases are the modified version of `dicom_sample1.zip` from [imageio/test_images](https://github.com/imageio/test_images/tree/main).
The [PR](https://github.com/imageio/test_images/pull/3) is created and wait to be merged, I may do the next step after it's done.

**Comment by FirefoxMetzger** [comment]
@Pandede I suspect that this is okay, but I have to ask anyway. Are you happy with us redistributing this image for testing purposes or (preferably) are you willing to release it under CC0?

**Comment by Pandede** [comment]
@FirefoxMetzger Sure, I may redistribute these images for testing purposes.

**Comment by FirefoxMetzger** [comment]
@Pandede I suspect that by "I" you mean we/ImageIO ... so under this assumption I will go ahead and merge the image :) If that was wrong let me know and I will adjust.

**Pull request merged**
